version: '3'
services:
  db:
    container_name: db
    image: postgres:13.11
    build:
      dockerfile: db.Dockerfile
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
  web:
    container_name: web
    build:
      dockerfile: web.Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
